baseURL = 'https://coderdojohelmond.nl'
languageCode = 'nl-nl'
title = 'CoderDojo Helmond'
theme = 'CoderDojo-Helmond-Theme'

[params]
  aanmeldLink = 'https://forms.office.com/Pages/ResponsePage.aspx?id=C5C-4TgS1UK9F-ukF3dwoJ0VjSJFQ41CmeBH81qRuBxUMk5ZTVpQVVAxUkRRMUFISDVMU1ZERkY5WS4u'
  contactEmail = 'contact@coderdojohelmond.nl'
  color = "#FFB005"
  
[[params.navigation]]
  title = "Home"
  url = "/"

[[params.navigation]]
  title = "Edities"
  url = "/edities"

[[params.navigation]]
  title = "Bestuur"
  url = "/bestuur"

#[[params.navigation]]
#  title = "Mentoren"
#  url = "/mentoren"

[[params.navigation]]
  title = "Over ons"
  url = "/overons"

#[[params.navigation]]
#  title = "Sponsoren"
#  url = "/sponsoren"

[[params.navigation]]
  title = "Contact"
  url = "/contact"
