baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[params]
  aanmeldLink = 'https://example.com'
  contactEmail = 'contact@coderdojohelmond.nl'
  color = "#FFB005"

[[params.navigation]]
  title = "Home"
  url = "/"

[[params.navigation]]
  title = "Edities"
  url = "/edities"

[[params.navigation]]
  title = "Bestuur"
  url = "/bestuur"

[[params.navigation]]
  title = "Mentoren"
  url = "/mentoren"

[[params.navigation]]
  title = "Over ons"
  url = "/overons"

[[params.navigation]]
  title = "Sponsoren"
  url = "/sponsoren"

[[params.navigation]]
  title = "Contact"
  url = "/contact"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
